### ISSUE TITLE
resolve_handle redirecting STDERR to /dev/null masks errors

### ISSUE THREAD

**Issue by jcoyne** [mbklein/handle#3]
https://github.com/mbklein/handle/blob/master/lib/handle/command/connection.rb#L109

The gem attempts to parse the output for errors, but the output is empty. The expected output was on STDERR

```
NoMethodError: undefined method `scan' for nil:NilClass
/foo/shared/bundle/ruby/2.1.0/bundler/gems/handle-75986eeedaa9/lib/handle/command/connection.rb:117:in `resolve_handle'
/foo/shared/bundle/ruby/2.1.0/bundler/gems/handle-75986eeedaa9/lib/handle/command/persistence.rb:31:in `save'
```

The command that is run looks like this:

```
/foo/gems/handle-75986eeedaa9/vendor/handle/bin/hdl-qresolver 10427.TEXX/000036 2> /dev/null
```

The STDERR has this:

```
    received HDL-UDP response: Error(100): HANDLE NOT FOUND

Error: HandleException (SERVICE_NOT_FOUND) Unable to find service for prefix 0.NA/10427.TEXX; prefix resolution response: Error(100): HANDLE NOT FOUND
HandleException (SERVICE_NOT_FOUND) Unable to find service for prefix 0.NA/10427.TEXX; prefix resolution response: Error(100): HANDLE NOT FOUND
    at net.handle.hdllib.HandleResolver.tryAuthGlobalServiceLookupAndThrowExceptionOnFailure(HandleResolver.java:804)
    at net.handle.hdllib.HandleResolver.findDelegatedPrefixService(HandleResolver.java:882)
    at net.handle.hdllib.HandleResolver.findPrefixService(HandleResolver.java:861)
    at net.handle.hdllib.HandleResolver.getServiceInfo(HandleResolver.java:842)
    at net.handle.hdllib.HandleResolver.findLocalSites(HandleResolver.java:948)
    at net.handle.hdllib.HandleResolver.processRequestGlobally(HandleResolver.java:618)
    at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:593)
    at net.handle.hdllib.HandleResolver.processRequest(HandleResolver.java:603)
    at net.handle.apps.simple.HDLTrace.<init>(HDLTrace.java:60)
    at net.handle.apps.simple.HDLTrace.main(HDLTrace.java:85)
```

**Comment by jcoyne** [comment]
The code presently works for a `HANDLE NOT FOUND`, but not for a service (handle prefix) not found.

**Comment by jcoyne** [comment]
It looks to me like this is a bug in net.handle.hdllib.HandleResolver because there is a comment in net.handle.apps.simple.HDLTrace that says:

>  // Should only reach here if there is an internal error
>  System.err.println("\nError: "+t);

It's unclear to me how this should be fixed.
